# The version property is now optional in modern Docker Compose
# version: '3.8'

name: wwebjs-api

services:
  app:
    container_name: wwebjs_api
    build: . # Build from the ./Dockerfile
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # --- Application Environment Variables ---
      - BASE_WEBHOOK_URL=http://localhost:3000/localCallbackExample
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE
      - MAX_ATTACHMENT_SIZE=5000000
      - SET_MESSAGES_AS_SEEN=TRUE
      - DISABLED_CALLBACKS=message_ack|message_reaction
      - ENABLE_SWAGGER_ENDPOINT=TRUE
      # - API_KEY=your_global_api_key_here
      # - RATE_LIMIT_MAX=1000
      # - RATE_LIMIT_WINDOW_MS=1000
      # - WEB_VERSION='2.2328.5'
      # - WEB_VERSION_CACHE_TYPE=none
      # - RECOVER_SESSIONS=TRUE
    volumes:
      - ./sessions:/usr/src/app/sessions # Keep this volume for your app data
    healthcheck:
      test: CMD-SHELL curl -fs http://localhost:3000/ping | jq -e '.success == true'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  health-monitor:
    container_name: wwebjs_monitor
    build:
      context: ./health-monitor
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    environment:
      # --- Monitor Configuration ---
      - TARGET_CONTAINER_NAME=wwebjs_api
      - CHECK_INTERVAL_SECONDS=60
      - EMAIL_SUBJECT_PREFIX=[WWebJS Health Alert]
      # --- Other Configuration ---
    depends_on:
      app:
        condition: service_started

# volumes:                    
#  ssmtp_config:
